/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package funWithAnnotations;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

import funWithAnnotations.SomeChildClass;
import funWithAnnotations.SomeParentClass;

public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
		SomeParentClass classUnderTest = new SomeChildClass("test const param");
		assertEquals("should be equal", "field : param test const param : ", classUnderTest.someLibraryMethod(""));
	}

	@Test
	@SuppressWarnings(value = { "deprecation" }) // testing suppression annotation
	public void testSomeClassGetField() {
		System.out.println("here's some output");
		SomeChildClass classUnderTest = new SomeChildClass("test const param");
		assertEquals("should be equal", "test const param", classUnderTest.getField());

	}
}
